language: ruby
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-latex-base texlive-latex-recommended
before_script:
  - psql -c 'create database travis;' -U postgres
after_failure:
  - "pwd"
  - "cat ./spec/tmp/latex.err"
  - "cat ./spec/tmp/example1.log"
  - "cat ./spec/tmp/psql.out"
bundler_args: --without debug
services:
  - postgresql
rvm:
  - 2.2.2
  - 2.3
  - 2.4
  - ruby-head
