language: ruby
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-latex-base
bundler_args: --without debug
services:
  postgresql
rvm:
  - 2.2.2
  - 2.3
  - 2.4
  - ruby-head
